# MAP() APLICA UMA FUNÇÃO A CADA ELEMENTO DE UMA ESTRUTURA DE DADOS INTERÁVEIS.
# A FUNÇÃO MAP() PEGA A FUNÇÃO SOMAR() E APLICA A SUA LÓGICA A CADA VALOR DA LISTA NÚMEROS.
# EXEMPLO: A FUNÇÃO SOMAR() PEGA CADA VALOR DA LISTA E SOMA + 2.
x = list(map(somar, numeros)) 



# DIFERENTE DE MAP(), RETORNA UM VALOR (A SOMA DOS VALORES DA LISTA)
from functools import reduce
y = reduce(soma,numeros)



# RETORNA APENAS OS VALORES QUE RESPEITAM A CONDIÇÃO DA FUNÇÃO PAR() - VERIFICA SE O NÚMERO É PAR
z = list(filter(par, lista))


# A FUNÇÃO ZIP() UNE VALORES DE VÁRIAS LISTAS EM PARES (PRIMEIRO COM PRIMEIRO, SEGUNDO COM SEGUNDO, ...)
# A FUNÇÃO DESCARTA VALORES RESTANTES SE AS LISTAS NÃO POSSUIREM O MESMO NÚMERO DE ELEMENTOS
lista3 = list(zip(lista1, lista2))
